image: continuumio/anaconda3

stages:
  - test

before_script:
  - python -V # Print out python version for debugging
  - conda env create --name mchad -f environment.yaml
  - pip install twine cython
  - pip install libmr
  - pip freeze # print package versions for debugging
  - export PYTHONPATH="src/"

test:
  script:
    - python -m unittest discover -s tests
    - echo "Calculating test coverage for the project."
    - pip install coverage
    - coverage run -m unittest discover
    - coverage report -m
    - coverage html
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"
  artifacts:
    paths:
      - htmlcov/
