image: continuumio/anaconda3:2022.05

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - test

before_script:
  - python -V # Print out python version for debugging
  - apt-get update
  - apt-get install -y gcc
  - conda env create --name mchad -f environment.yaml
  - conda activate mchad
    # these would lead to conflicts or have been installed later
  - pip install aiohttp==3.7 async-timeout==3.0.1 tensorboardX==2.5.1
  - pip freeze # print package versions for debugging
  - export PYTHONPATH="src/"

test:
  script:
    - python -m unittest discover -s tests
    - echo "Calculating test coverage for the project."
    - pip install coverage
    - coverage run -m unittest discover
    - coverage report -m
    - coverage html
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"
  artifacts:
    paths:
      - htmlcov/
