# define test cases for models trained on the cifar-100

test_vs_textures:
  _target_: src.datamodules.ood_datamodule.OODDataModule
  normalize:
    # https://github.com/wetliu/energy_ood/blob/master/CIFAR/train.py
    mean: [ 0.49137254901960784313, 0.48235294117647058823, 0.44666666666666666666 ]
    std: [ 0.24705882352941176470, 0.24352941176470588235, 0.26156862745098039215 ]
  data_in:
    _target_: torchvision.datasets.CIFAR100
    root: ${data_dir}
    train: False
    download: True
  data_out:
    _target_: pytorch_ood.dataset.img.Textures
    root: ${data_dir}
    download: True
test_vs_uniformnoise:
  _target_: src.datamodules.ood_datamodule.OODDataModule
  normalize:
    # https://github.com/wetliu/energy_ood/blob/master/CIFAR/train.py
    mean: [ 0.49137254901960784313, 0.48235294117647058823, 0.44666666666666666666 ]
    std: [ 0.24705882352941176470, 0.24352941176470588235, 0.26156862745098039215 ]
  data_in:
    _target_: torchvision.datasets.CIFAR100
    root: ${data_dir}
    train: False
    download: True
  data_out:
    _target_: pytorch_ood.dataset.img.UniformNoise
    length: 10000
    size: [32, 32, 3]
test_vs_gaussiannoise:
  _target_: src.datamodules.ood_datamodule.OODDataModule
  normalize:
    # https://github.com/wetliu/energy_ood/blob/master/CIFAR/train.py
    mean: [ 0.49137254901960784313, 0.48235294117647058823, 0.44666666666666666666 ]
    std: [ 0.24705882352941176470, 0.24352941176470588235, 0.26156862745098039215 ]
  data_in:
    _target_: torchvision.datasets.CIFAR100
    root: ${data_dir}
    train: False
    download: True
  data_out:
    _target_: pytorch_ood.dataset.img.GaussianNoise
    length: 10000
    size: [32, 32, 3]

test_vs_tinycrop:
  _target_: src.datamodules.ood_datamodule.OODDataModule
  normalize:
    # https://github.com/wetliu/energy_ood/blob/master/CIFAR/train.py
    mean: [ 0.49137254901960784313, 0.48235294117647058823, 0.44666666666666666666 ]
    std: [ 0.24705882352941176470, 0.24352941176470588235, 0.26156862745098039215 ]
  data_in:
    _target_: torchvision.datasets.CIFAR100
    root: ${data_dir}
    train: False
    download: True
  data_out:
    _target_: pytorch_ood.dataset.img.TinyImageNetCrop
    root: ${data_dir}
    download: True
test_vs_tinyresize:
  _target_: src.datamodules.ood_datamodule.OODDataModule
  normalize:
    # https://github.com/wetliu/energy_ood/blob/master/CIFAR/train.py
    mean: [ 0.49137254901960784313, 0.48235294117647058823, 0.44666666666666666666 ]
    std: [ 0.24705882352941176470, 0.24352941176470588235, 0.26156862745098039215 ]
  data_in:
    _target_: torchvision.datasets.CIFAR100
    root: ${data_dir}
    train: False
    download: True
  data_out:
    _target_: pytorch_ood.dataset.img.TinyImageNetResize
    root: ${data_dir}
    download: True
test_vs_lsuncrop:
  _target_: src.datamodules.ood_datamodule.OODDataModule
  normalize:
    # https://github.com/wetliu/energy_ood/blob/master/CIFAR/train.py
    mean: [ 0.49137254901960784313, 0.48235294117647058823, 0.44666666666666666666 ]
    std: [ 0.24705882352941176470, 0.24352941176470588235, 0.26156862745098039215 ]
  data_in:
    _target_: torchvision.datasets.CIFAR100
    root: ${data_dir}
    train: False
    download: True
  data_out:
    _target_: pytorch_ood.dataset.img.LSUNCrop
    root: ${data_dir}
    download: True
test_vs_lsunresize:
  _target_: src.datamodules.ood_datamodule.OODDataModule
  normalize:
    # https://github.com/wetliu/energy_ood/blob/master/CIFAR/train.py
    mean: [ 0.49137254901960784313, 0.48235294117647058823, 0.44666666666666666666 ]
    std: [ 0.24705882352941176470, 0.24352941176470588235, 0.26156862745098039215 ]
  data_in:
    _target_: torchvision.datasets.CIFAR100
    root: ${data_dir}
    train: False
    download: True
  data_out:
    _target_: pytorch_ood.dataset.img.LSUNResize
    root: ${data_dir}
    download: True
