_target_: src.datamodules.ood_datamodule
data_dir: ${data_dir} # data_dir is specified in config.yaml
batch_size: 128
#train_val_test_split: [45_000, 10_000, 10_000]
num_workers: 10
pin_memory: False

data_in:
  _target_: src.datamodules.cifar10_datamodule.CIFAR10DataModule
data_out:
  _target_: src.datamodules.ood_datamodule.OODDataModule
