# define test cases for models trained on the SVHN
test_vs_textures:
  _target_: src.datamodules.ood_datamodule.OODDataModule
  normalize:
    # https://albumentations.ai/docs/autoalbument/examples/svhn/
    mean: [0.4376821, 0.4437697, 0.47280442]
    std: [0.19803012, 0.20101562, 0.19703614]
  data_in:
    _target_: torchvision.datasets.SVHN
    root: ${data_dir}
    split: "test"
    download: True
  data_out:
    _target_: src.datamodules.datasets.textures.Textures
    root: ${data_dir}
    download: True
test_vs_uniformnoise:
  _target_: src.datamodules.ood_datamodule.OODDataModule
  normalize:
    # https://albumentations.ai/docs/autoalbument/examples/svhn/
    mean: [0.4376821, 0.4437697, 0.47280442]
    std: [0.19803012, 0.20101562, 0.19703614]
  data_in:
    _target_: torchvision.datasets.SVHN
    root: ${data_dir}
    split: "test"
    download: True
  data_out:
    _target_: src.datamodules.datasets.noise.UniformNoise
    samples: 10000
    size: [32, 32, 3]
test_vs_gaussiannoise:
  _target_: src.datamodules.ood_datamodule.OODDataModule
  normalize:
    # https://albumentations.ai/docs/autoalbument/examples/svhn/
    mean: [0.4376821, 0.4437697, 0.47280442]
    std: [0.19803012, 0.20101562, 0.19703614]
  data_in:
    _target_: torchvision.datasets.SVHN
    root: ${data_dir}
    split: "test"
    download: True
  data_out:
    _target_: src.datamodules.datasets.noise.GaussianNoise
    samples: 10000
    size: [32, 32, 3]
test_vs_tinycrop:
  _target_: src.datamodules.ood_datamodule.OODDataModule
  normalize:
    # https://albumentations.ai/docs/autoalbument/examples/svhn/
    mean: [0.4376821, 0.4437697, 0.47280442]
    std: [0.19803012, 0.20101562, 0.19703614]
  data_in:
    _target_: torchvision.datasets.SVHN
    root: ${data_dir}
    split: "test"
    download: True
  data_out:
    _target_: src.datamodules.datasets.odin.TinyImageNetCrop
    root: ${data_dir}
    download: True
test_vs_tinyresize:
  _target_: src.datamodules.ood_datamodule.OODDataModule
  normalize:
    # https://albumentations.ai/docs/autoalbument/examples/svhn/
    mean: [0.4376821, 0.4437697, 0.47280442]
    std: [0.19803012, 0.20101562, 0.19703614]
  data_in:
    _target_: torchvision.datasets.SVHN
    root: ${data_dir}
    split: "test"
    download: True
  data_out:
    _target_: src.datamodules.datasets.odin.TinyImageNetResize
    root: ${data_dir}
    download: True
test_vs_lsuncrop:
  _target_: src.datamodules.ood_datamodule.OODDataModule
  normalize:
    # https://albumentations.ai/docs/autoalbument/examples/svhn/
    mean: [0.4376821, 0.4437697, 0.47280442]
    std: [0.19803012, 0.20101562, 0.19703614]
  data_in:
    _target_: torchvision.datasets.SVHN
    root: ${data_dir}
    split: "test"
    download: True
  data_out:
    _target_: src.datamodules.datasets.odin.LSUNCrop
    root: ${data_dir}
    download: True
test_vs_lsunresize:
  _target_: src.datamodules.ood_datamodule.OODDataModule
  normalize:
    # https://albumentations.ai/docs/autoalbument/examples/svhn/
    mean: [0.4376821, 0.4437697, 0.47280442]
    std: [0.19803012, 0.20101562, 0.19703614]
  data_in:
    _target_: torchvision.datasets.SVHN
    root: ${data_dir}
    split: "test"
    download: True
  data_out:
    _target_: src.datamodules.datasets.odin.LSUNResize
    root: ${data_dir}
    download: True
