defaults:
  - default.yaml

softmax:
  _target_: src.callbacks.softmax.SoftmaxThresholding
  use_in_val: True
  use_in_test: True

distance:
  _target_: src.callbacks.distance.DistanceThresholding
  use_in_val: True
  use_in_test: True
