defaults:
  - default.yaml

distance:
  _target_: src.callbacks.distance.DistanceThresholding
  use_in_val: True
  use_in_test: True

cac:
  _target_: src.callbacks.cac.CACScorer
  use_in_val: True
  use_in_test: True
