defaults:
  - default.yaml

softmax:
  _target_: src.callbacks.softmax.SoftmaxThresholding
  use_in_val: True
  use_in_test: True

#energy:
#  _target_: src.callbacks.energy.EnergyBased
#  temperature: 1
#  use_in_val: True
#  use_in_test: True

#  mcd:
#    _target_: src.callbacks.mcd.MonteCarloDropout
#    num_classes: 10
#    rounds: 30
#    use_in_val: False
#    use_in_test: True
#  openmax:
#    _target_: src.callbacks.openmax.OpenMax
#    tailsize: 3
#    alpha: 3
#    euclid_weight: 0
#    use_in_val: False
#    use_in_test: True
#  odin:
#    _target_: src.callbacks.odin.ODIN
#    eps: 0.02
#    t: 1000
#    use_in_val: False
#    use_in_test: True
#  tscaling:
#    _target_: src.callbacks.tscaling.TemperatureScaling
#    temperature: 1000
#    use_in_val: True
#    use_in_test: True
