_target_: src.datamodules.MultiDatamodule
module1:
  _target_: src.datamodules.CIFAR10DataModule
  normalize:
    # https://github.com/wetliu/energy_ood/blob/master/CIFAR/train.py
    mean:
      [0.49137254901960784313, 0.48235294117647058823, 0.44666666666666666666]
    std:
      [0.24705882352941176470, 0.24352941176470588235, 0.26156862745098039215]
  data_dir: ${data_dir}
  batch_size: 128
  num_workers: 20
  pin_memory: False
  data_order_seed: null
  data_split_seed: null
module2:
  _target_: src.datamodules.SingleOODDataModule
  dataset:
    _target_: src.datamodules.datasets.TinyImages300k
    datafile: ${dataset_dir}/tiny-images/300K_random_images.npy
  #    _target_: src.datamodules.datasets.TinyImages
  #    datafile: ${dataset_dir}/tiny-images/tiny_images.bin
  #    cifar_index_file: ${dataset_dir}/tiny-images/80mn_cifar_idxs.txt
  #    exclude_cifar: True
  normalize:
    # https://github.com/wetliu/energy_ood/blob/master/CIFAR/train.py
    mean:
      [0.49137254901960784313, 0.48235294117647058823, 0.44666666666666666666]
    std:
      [0.24705882352941176470, 0.24352941176470588235, 0.26156862745098039215]
  batch_size: 256
  num_workers: 20
  pin_memory: False
  data_order_seed: null
  data_split_seed: null
