_target_: src.datamodules.mnist_datamodule.MNISTDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
batch_size: 128
train_val_test_split: [55_000, 5_000, 10_000]
num_workers: 10
pin_memory: False
