_target_: src.datamodules.multi_datamodule.MultiDatamodule
module1:
  _target_: src.datamodules.SVHNDataModule
  normalize:
    # https://albumentations.ai/docs/autoalbument/examples/svhn/
    mean: [0.4376821, 0.4437697, 0.47280442]
    std: [0.19803012, 0.20101562, 0.19703614]
  data_dir: ${data_dir}
  batch_size: 128
  num_workers: 20
  pin_memory: False
  data_order_seed: null
  data_split_seed: null
module2:
  _target_: src.datamodules.ood_datamodule.SingleOODDataModule
  dataset:
    _target_: torchvision.datasets.ImageFolder
    root: ${data_dir}/mini-imagenet-full-32x32
  normalize:
    # https://albumentations.ai/docs/autoalbument/examples/svhn/
    mean: [0.4376821, 0.4437697, 0.47280442]
    std: [0.19803012, 0.20101562, 0.19703614]
  batch_size: 256
  num_workers: 20
  pin_memory: False
  data_order_seed: null
  data_split_seed: null